### ISSUE TITLE
Stopping server does not actually skill server process 

### ISSUE THREAD

**Issue by kantord** [kantord/SeaGOAT#210]
This should be fairly simple to solve. We already have a test for stopping the server:

https://github.com/kantord/SeaGOAT/blob/0356687f2cebd9a14c834d0a11ce9f12f77e60b9/tests/test_server.py#L127-L143

The only thing wrong with this test that it does not test that the server process is actually killed. And it seems like the implementation for the server stopping command does not actually kill the server process, it just does some things that fool the test:

https://github.com/kantord/SeaGOAT/blob/0356687f2cebd9a14c834d0a11ce9f12f77e60b9/seagoat/server.py#L184-L199

The correct way to solve it is by:

1. Making sure that the tests fails because the server process is not being killed
2. After seeing that the tests "fails correctly" fix the implementation and make sure that the tests now pass

The `get_server_info` function should already return the process ID, so you should be able to use that in the test in order to make sure that the process is running before the server is killed and that it is not running after it's killed. Also, you should be able to use that to actually kill the server process in the implementation!

**Comment by tbetous** [comment]
Hello @kantord !

I would like to make it for the hacktoberfest event. Can you assign me on this ?

Is that ok to include the part part to terminate the process in `remove_server_info` function in the `seagoat/utils/server.py` file? 

To me it sounds ok to consider that removing server info also terminate the process.

--- 

Aside, nice project here! I'll probably give it a try in my next open source project. :+1:

**Comment by kantord** [comment]
> Hello @kantord !
> 
> I would like to make it for the hacktoberfest event. Can you assign me on this ?
> 
> Is that ok to include the part part to terminate the process in `remove_server_info` function in the `seagoat/utils/server.py` file?
> 
> To me it sounds ok to consider that removing server info also terminate the process.
> 
> Aside, nice project here! I'll probably give it a try in my next open source project. 👍

Sure, that sounds good to me. Though in that case I would probably rename the function to something more appropriate like `stop_server`

**Comment by Jatinjain07Dazai** [comment]
Can i work on this issue  ?

**Comment by kantord** [comment]
> Can i work on this issue ?

hi @Jatinjain07Dazai looks like @tbetous is already working on it, maybe you can ask him if he needs any help? Or stay tuned, I will try to create more tasks
