### ISSUE TITLE
gt reports that SeaGOAT server is not running when in fact it does

### ISSUE THREAD

**Issue by stillonearth** [kantord/SeaGOAT#229]
I've followed a README and started a server in one tab, it indexed the repo and then outputs 
```bash
Analyzing source code: 0it [00:00, ?it/s]
2023-09-20 20:37:42,312 Analyzed the minimum number of chunks needed to operate. 
2023-09-20 20:37:42,312 Analyzed all chunks!
```

In another ttab running an example query fails

```bash
gt "Where are the numbers rounded"
The SeaGOAT server is not running. Please start the server using the following command:

seagoat-server start /home/git/repo
```

**Comment by stelf** [comment]
restarting the term session actually fixes this, not sure why

**Comment by kantord** [comment]
yeah, one thing to keep in mind is that each server is associated with a repo path, and you can run multiple servers.

It could be useful to show a warning that the server is not running for the current repo, but it is running for different repos maybe?

**Comment by stillonearth** [comment]
@GautierT it should have worked that way, but now server throws

```
Exception in thread Thread-1 (_worker_function):
Traceback (most recent call last):
  File "/home/cwiz/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/cwiz/anaconda3/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 79, in _worker_function
    self._handle_task(context, task)
  File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 66, in _handle_task
    result = handler(context, *task.args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 83, in handle_query
    results = context["seagoat_engine"].get_results(kwargs["limit_clue"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 208, in get_results
    sorted(
  File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 212, in <lambda>
    + 0.3 * normalize_file_position(top_files[x.p
```

It seems another unrelated issue.

**Comment by kantord** [comment]
> @GautierT it should have worked that way, but now server throws
> 
> ```
> Exception in thread Thread-1 (_worker_function):
> Traceback (most recent call last):
>   File "/home/cwiz/anaconda3/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/home/cwiz/anaconda3/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 79, in _worker_function
>     self._handle_task(context, task)
>   File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/base_queue.py", line 66, in _handle_task
>     result = handler(context, *task.args, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/queue/task_queue.py", line 83, in handle_query
>     results = context["seagoat_engine"].get_results(kwargs["limit_clue"])
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 208, in get_results
>     sorted(
>   File "/home/cwiz/.local/pipx/venvs/seagoat/lib/python3.11/site-packages/seagoat/engine.py", line 212, in <lambda>
>     + 0.3 * normalize_file_position(top_files[x.p
> ```
> 
> It seems another unrelated issue.

that one should be fixed now, please report it if you face it again with the latest version

**Comment by stillonearth** [comment]
Yes, it works now.
