### ISSUE TITLE
Allow users to configure ONNX execution provider to increase embedding generation

### ISSUE THREAD

**Issue by ashishdatta** [kantord/SeaGOAT#293]
I see that the default model SeaGOAT is using to generate the embeddings is the [ONNX model](https://github.com/chroma-core/chroma/blob/fc4c8b547444efafa8ddf75fbd53a9b8e1a7eabe/chromadb/utils/embedding_functions.py#L240)

ChromaDB allows for users to [set](https://github.com/chroma-core/chroma/blob/fc4c8b547444efafa8ddf75fbd53a9b8e1a7eabe/chromadb/utils/embedding_functions.py#L253) the ONNX execution providers to gain some increase embedding generation speedup.

I was wondering if it would make sense to make this a configurable parameter set in the config file for SeaGOAT. I have been doing some testing on my [fork](https://github.com/ashishdatta/SeaGOAT/tree/embedding_test) around the OpenVINO execution provider and I see some great speedup and more efficient CPU load. Would be happy to continue working on it, just wanted to check if this is something SeaGOAT wants to support.

More info on ONNX execution providers can be found here: https://onnxruntime.ai/docs/execution-providers/

**Comment by kantord** [comment]
Yeah, I think it would make sense to make this configurable for sure. Or maybe to even introduce some automagic configuration

**Comment by kantord** [comment]
ok, so this issue is almost done, the only thing remaining I think is to document this use case

**Comment by kantord** [comment]
done, documented here: https://kantord.github.io/SeaGOAT/0.36.x/configuration/#server
