### ISSUE TITLE
Task queue priority should be based on file importance

### ISSUE THREAD

**Issue by kantord** [kantord/SeaGOAT#300]
At the moment, it seems like the task queue order is kinda random:

```
2023-10-07 16:12:12,329 Processing chunk <FileChunk tests/functional/dashboard/test_category.py 28>...
2023-10-07 16:12:12,733 Handling task: analyze_chunk
2023-10-07 16:12:12,733 Note, 25086 tasks left in the queue.
2023-10-07 16:12:12,733 Processing chunk <FileChunk src/oscar/apps/order/migrations/0001_initial.py 314>...
2023-10-07 16:12:13,095 Handling task: analyze_chunk
2023-10-07 16:12:13,095 Note, 25085 tasks left in the queue.
2023-10-07 16:12:13,096 Processing chunk <FileChunk src/oscar/apps/order/migrations/0001_initial.py 302>...
2023-10-07 16:12:13,562 Handling task: analyze_chunk
2023-10-07 16:12:13,562 Note, 25084 tasks left in the queue.
2023-10-07 16:12:13,562 Processing chunk <FileChunk src/oscar/apps/payment/abstract_models.py 318>...
2023-10-07 16:12:13,889 Handling task: analyze_chunk
2023-10-07 16:12:13,890 Note, 25083 tasks left in the queue.
2023-10-07 16:12:13,890 Processing chunk <FileChunk src/oscar/apps/customer/alerts/utils.py 117>...
2023-10-07 16:12:14,185 Handling task: analyze_chunk
2023-10-07 16:12:14,185 Note, 25082 tasks left in the queue.
2023-10-07 16:12:14,185 Processing chunk <FileChunk tests/functional/customer/test_order_status.py 6>...
```

Instead it should be based on the importance of the file, **because we want to process the most important files in the repo first**!

This is the code where these tasks are added to the queue:

https://github.com/kantord/SeaGOAT/blob/3c0d9279c33384c2cde77f327e8b85f26e2ea5db/seagoat/queue/task_queue.py#L74-L77

**`remaining_chunks_to_analyze` already returns the chunks in the correct order**, but as you can see, all of these tasks are added using `priority=LOW_PRIORITY`. This queue used to be a FIFO queue, so tasks were processed in the correct order by default. However now they are processed in a random order.

Existing priorities are defined here:
https://github.com/kantord/SeaGOAT/blob/3c0d9279c33384c2cde77f327e8b85f26e2ea5db/seagoat/queue/base_queue.py#L12-L13

We could probably introduce a medium priority like this:

```diff
HIGH_PRIORITY = 0
+MEDIUM_PRIORITY = 0.5
LOW_PRIORITY = 1 
```

Then we could make sure that each task is added with the correct priority. For example. if we have 6 tasks, they could be added with the following priorities:

> 0.5, 0.6, 0.7, 0.8, 0.9, 1.0

So somehow if we have X tasks, the formula could be something like (pseudo code!)

```
priority(task_index) => MEDIUM_PRIORITY + ((LOW_PRIORITY - MEDIUM_PRIORITY) / len(X) * task_index)
```

I guess the code that adds the tasks will change something like this (pseudo code):]

```python
 for task_id, chunk in enumerate(remaining_chunks_to_analyze):
     # write actual formula, this is untested 👇
     priority = MEDIUM_PRIORITY + ((LOW_PRIORITY - MEDIUM_PRIORITY) / len(X) * task_index)
     self.enqueue( 
         "analyze_chunk", chunk, priority=priority, wait_for_result=False 
     ) 
```

_It is also important to write a test that verifies this behavior. **The test should fail with the current implementation**_ There are different potential approaches to testing this, but maybe the easiest way is to basically copy paste this test:

https://github.com/kantord/SeaGOAT/blob/3c0d9279c33384c2cde77f327e8b85f26e2ea5db/tests/test_server.py#L74-L94

then get the list of files not analyzed yet. That can be done by easily by creating a new `Engine` object in the same repo and checking the `chunks_not_yet_analyzed` value. Code example:

```python
my_engine = Engine(repo_with_more_files.working_dir)
list_of_chunks_not_cached = my_engine.cache["chunks_not_yet_analyzed"]
all_vector_embeddings = my_engine._create_vector_embeddings()
top_files = list(my_engine.repository.top_files())

files_not_yet_analyzed = { chunk.path for chunk in all_vector_embeddings if chunk.id in list_of_chunks_not_cached }
```

Then you can make an assertion to make sure that the files that are not analyzed yet are the files that are least important (i. e. they are at the end of the top_files list):

```python
assert {file['path'] for file in top_files[-len(files_not_yet_analyzed):]} == files_not_yet_analyzed
```

**Comment by agnes-sharan** [comment]
Hi is this open for contribution?

**Comment by kantord** [comment]
Hi @agnes-sharan yes, absolutely, go for it!

**Comment by kantord** [comment]
also if you get stuck or need some info, feel free to schedule a call with me https://calendly.com/kantord/30-minute-call

**Comment by bermr** [comment]
Hi! I would like to work on this issue.

**Comment by Cretus-iosDev** [comment]
Hi @kantord  
I have generated the PR pls check it, and let me know if any changes are needed.
waiting for your reply.
