### ISSUE TITLE
Replace `pylint` and `black` with `ruff`

### ISSUE THREAD

**Issue by kantord** [kantord/SeaGOAT#352]
Ruff is a faster alternative to `pylint` and `black` and it replaces both tools. We should replace those tools with `ruff` in our pre-commit configuration.

Link to ruff documentation: https://github.com/astral-sh/ruff

**Comment by 0scvr** [comment]
Please assign me the issue. I'd like to work on this.

**Comment by kantord** [comment]
Go for it @0scvr

**Comment by 0scvr** [comment]
> Go for it @0scvr

Thank you. Do you need `ruff` to just check for issues or fix them as well ?

**Comment by kantord** [comment]
> > Go for it @0scvr
> 
> Thank you. Do you need `ruff` to just check for issues or fix them as well ?

fix would be nice. right now `black` is being used for autofixing issues. it would be nice to be able to autofix as many things as possible

**Comment by 0scvr** [comment]
> > > Go for it @0scvr
> > 
> > 
> > Thank you. Do you need `ruff` to just check for issues or fix them as well ?
> 
> fix would be nice. right now `black` is being used for autofixing issues. it would be nice to be able to autofix as many things as possible

Ok, I can do that. Lastly, am I correct in assuming the `typings` folder should be excluded from ruff checks ?

**Comment by kantord** [comment]
> > > > Go for it @0scvr
> > > 
> > > 
> > > Thank you. Do you need `ruff` to just check for issues or fix them as well ?
> > 
> > 
> > fix would be nice. right now `black` is being used for autofixing issues. it would be nice to be able to autofix as many things as possible
> 
> Ok, I can do that. Lastly, am I correct in assuming the `typings` folder should be excluded from ruff checks ?

yes, absolutely. those are not manually written files
